import { vi } from "vitest";
import type { AssetCard, AssetDetail } from "../types";
import type { FilterBarState, LibraryActions } from "../lib/libraryActions";

export const sampleCard: AssetCard = {
  id: 1,
  file_name: "photo.jpg",
  ext: "jpg",
  kind: "image",
  capture_at: null,
  rating: null,
  sync_state: "ok",
  thumb_path: "/tmp/1.webp",
  abs_path: "/tmp/1.jpg",
  has_duplicate: false,
};

export const sampleVideoCard: AssetCard = {
  ...sampleCard,
  id: 2,
  file_name: "clip.mp4",
  ext: "mp4",
  kind: "video",
  thumb_path: null,
  abs_path: "/tmp/2.mp4",
};

export const sampleDetail: AssetDetail = {
  asset: {
    id: 1,
    root_id: 1,
    rel_path: "photo.jpg",
    file_name: "photo.jpg",
    ext: "jpg",
    kind: "image",
    size: 1024,
    mtime_ns: 0,
    sync_state: "ok",
  },
  meta: null,
  abs_path: "/tmp/1.jpg",
  display_path: "/tmp/1.jpg",
  tag_ids: [1],
  album_ids: [],
  raw_tags: [{ name: "Make", value: "Sony" }],
  links: [],
  duplicates: [],
};

export const emptyFilterBar: FilterBarState = {
  ratingMin: "",
  syncStates: [],
  deleteStatus: "",
  camera: "",
  tagIds: [],
  albumIds: [],
  metaSearch: "",
  hasGps: false,
  hasDuplicate: false,
  captureFrom: "",
  captureTo: "",
  sort: "date",
  sortDir: "desc",
};

export function mockLibraryActions(): LibraryActions {
  return {
    addLocalRoot: vi.fn(),
    addMountedSmbPath: vi.fn(),
    openSmbConnect: vi.fn(),
    connectSmbShare: vi.fn(),
    removeRoot: vi.fn(),
    syncRoot: vi.fn(),
    selectRoot: vi.fn(),
    clearFilters: vi.fn(),
    openExport: vi.fn(),
    createAlbum: vi.fn(),
    deleteAlbum: vi.fn(),
    selectAlbum: vi.fn(),
    selectCollection: vi.fn(),
    deleteCollection: vi.fn(),
    relinkRoot: vi.fn(),
    selectAsset: vi.fn(),
    openLinked: vi.fn(),
    rate: vi.fn(),
    batchRate: vi.fn(),
    openTagMenu: vi.fn(),
    openAlbumMenu: vi.fn(),
    toggleTagOnSelection: vi.fn(),
    createTagOnSelection: vi.fn(),
    toggleAlbumOnSelection: vi.fn(),
    createAlbumOnSelection: vi.fn(),
    batchRemove: vi.fn(),
    batchPurge: vi.fn(),
    softDeleteDuplicate: vi.fn(),
    softDelete: vi.fn(),
    purge: vi.fn(),
    submitPurge: vi.fn(),
    restoreSelected: vi.fn(),
    saveCollection: vi.fn(),
    submitSaveCollection: vi.fn(),
    openGallery: vi.fn(),
    closeDetail: vi.fn(),
    closeInspector: vi.fn(),
    clearSelection: vi.fn(),
    loadMore: vi.fn(),
    filterByTag: vi.fn(),
    createTag: vi.fn(),
    updateTag: vi.fn(),
    deleteTag: vi.fn(),
    updateAlbum: vi.fn(),
    viewTrash: vi.fn(),
    viewLibrary: vi.fn(),
    rebuildCatalog: vi.fn(),
    cancelScan: vi.fn(),
    navigateRelative: vi.fn(),
    navigateGrid: vi.fn(),
    adjustGridSize: vi.fn(),
    openFullView: vi.fn(),
    openFullViewFor: vi.fn(),
    closeFullView: vi.fn(),
    toggleFullscreen: vi.fn(),
    openCompare: vi.fn(),
    closeCompare: vi.fn(),
    rateAsset: vi.fn(),
    toggleTagOnAsset: vi.fn(),
    createTagOnAsset: vi.fn(),
    toggleAlbumOnAsset: vi.fn(),
    createAlbumOnAsset: vi.fn(),
    deleteAsset: vi.fn(),
    disarmStamp: vi.fn(),
    setStampRating: vi.fn(),
    toggleStampTag: vi.fn(),
    toggleStampAlbum: vi.fn(),
    toggleStampOnTargets: vi.fn(),
  };
}
